version: '3.3'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'police3'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Jack1994'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    container_name: mysql-db
